name: CD
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build -c Release src/CassandraMigrator.sln
    - name: Create NuGet packages
      run: dotnet pack -o dist/pkg -c Release --no-build src/CassandraMigrator.sln
    - name: Publish CLI
      run: dotnet publish -o dist/cli -c Release --no-build src/CassandraMigrator.Console
    - name: Publish Docker assets
      run: |
        mkdir -pv dist/docker/cli
        cp -v src/CassandraMigrator.Console/Dockerfile dist/docker/cli
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: dist/pkg
    - name: Upload CLI
      uses: actions/upload-artifact@v2
      with:
        name: cli
        path: dist/cli
    - name: Upload Docker assets
      uses: actions/upload-artifact@v2
      with:
        name: docker
        path: dist/docker
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v2
      with:
        name: packages
        path: packages
    - name: Download CLI
      uses: actions/download-artifact@v2
      with:
        name: cli
        path: cli
    - name: Download Docker assets
      uses: actions/download-artifact@v2
      with:
        name: docker
        path: docker
    - name: Get CLI version
      run: |
        version=$(dotnet cli/cassandra-migrator.dll --version)
        echo "::set-output name=version::$version"
      id: cli-version
    - name: Check if CLI image exists
      run: |
        exists="true"
        docker manifest inspect ultimicro/cassandra-migrator:${{ steps.cli-version.outputs.version }} &> /dev/null || exists="false"
        echo "::set-output name=exists::$exists"
      id: check-cli-image
    - name: Build CLI image
      run: |
        docker build -t ultimicro/cassandra-migrator:${{ steps.cli-version.outputs.version }} -f docker/cli/Dockerfile cli
        docker tag ultimicro/cassandra-migrator:${{ steps.cli-version.outputs.version }} ultimicro/cassandra-migrator:latest
      if: ${{ !steps.check-cli-image.outputs.exists }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: ${{ !steps.check-cli-image.outputs.exists }}
    - name: Push CLI image
      run: |
        docker push ultimicro/cassandra-migrator:${{ steps.cli-version.outputs.version }}
        docker push ultimicro/cassandra-migrator:latest
      if: ${{ !steps.check-cli-image.outputs.exists }}
    - name: Publish NuGet packages
      run: dotnet nuget push '*.nupkg' -s https://api.nuget.org/v3/index.json -k "${{ secrets.NUGET_KEY }}" --skip-duplicate
      working-directory: ./packages
